name = "DynamicElectricSheath"
uuid = "82a5a15b-6a31-4a23-a3d4-0d9b5065a506"
authors = ["Hivlashea team"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DocStringExtensions = "0.9"
