name = "FiniteDiffDynSheath"
uuid = "82a5a15b-6a31-4a23-a3d4-0d9b5065a506"
authors = ["Hivlashea team"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PerceptualColourMaps = "54e51dfa-9dd7-5231-aa84-a4037b83483a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
VideoIO = "d6d074c3-1acf-5d4c-9a43-ef38773959a2"
